service: vision
frameworkVersion: '4.1.16'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rekognition:DetectFaces"
        - "rekognition:DetectLabels"
        - "logs:*"
        - "s3:GetObject"
        - "bedrock:InvokeModel"  
      Resource: "*"

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v2Description:
    handler: handler.v2_description
    events:
      - httpApi:
          path: /v2
          method: get
  analyze_image_v1:
    handler: handler.analyze_image_v1
    events:
      - httpApi:
          path: /v1/vision
          method: post
  analyze_image_v2:
    handler: handler.analyze_image_v2
    events:
      - httpApi:
          path: /v2/vision
          method: post
